---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
    tier: back-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      tier: back-tier
  template:
    metadata:
      labels:
        app: postgres
        tier: back-tier
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-env-configmap
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
            - name: healthcheck
              mountPath: /healthchecks
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - /healthchecks/postgres.sh
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: db-data
          emptyDir: {} 
        - name: healthcheck
          configMap:
            name: postgres-healthcheck-configmap
            defaultMode: 0777
