---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result
    tier: front-tier
spec:
  selector:
    app: result
    tier: front-tier
  ports:
  - port: 80
    targetPort: 5001
