---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: vote
    tier: front-tier
spec:
  type: NodePort
  selector:
    app: vote
    tier: front-tier
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30001
