---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploymant
  labels:
    app: worker
    tier: back-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
      tier: back-tier
  template:
    metadata:
      labels:
        app: worker
        tier: back-tier
    spec:
      containers:
      - name: worker
        image: dockersamples/examplevotingapp_worker
